FROM node:22.18.0-bookworm-slim AS build

WORKDIR /app
COPY . .
RUN npm ci && npm run build

FROM node:22.18.0-bookworm-slim AS runtime

ENV NODE_ENV=production
WORKDIR /app
COPY --from=build /app /app
USER node
CMD ["node", "apps/api/dist/main.js"]
