#!/usr/bin/env bash

set -euo pipefail

ACTION="${1:-}"
RELEASE_DIR="${2:-}"
ENV_FILE="${3:-}"
PROJECT_NAME="spark-x-test-platform"

if [[ -z "$ACTION" || -z "$RELEASE_DIR" || -z "$ENV_FILE" ]]; then
  echo "usage: release.sh <backup|migrate|start|stop|smoke> <release-dir> <env-file>" >&2
  exit 64
fi

if [[ ! -d "$RELEASE_DIR" || ! -f "$RELEASE_DIR/infra/compose/compose.yaml" ]]; then
  echo "release directory is incomplete" >&2
  exit 65
fi

SHARED_DIR="$(dirname "$ENV_FILE")"

ensure_runtime_environment() {
  mkdir -p "$SHARED_DIR"
  chmod 700 "$SHARED_DIR"
  if [[ -f "$ENV_FILE" ]]; then
    return 0
  fi

  command -v openssl >/dev/null
  umask 077
  local postgres_password
  local minio_secret
  local platform_secret_key
  postgres_password="$(openssl rand -hex 32)"
  minio_secret="$(openssl rand -hex 32)"
  platform_secret_key="$(openssl rand -base64 32 | tr -d '\n')"
  {
    printf 'NODE_ENV=production\n'
    printf 'LOG_LEVEL=info\n'
    printf 'WEB_PORT=4173\n'
    printf 'API_PORT=24100\n'
    printf 'SCHEDULER_HEALTH_PORT=24101\n'
    printf 'WORKER_HEALTH_PORT=24102\n'
    printf 'POSTGRES_PORT=25432\n'
    printf 'REDIS_PORT=26379\n'
    printf 'MINIO_PORT=29000\n'
    printf 'MINIO_CONSOLE_PORT=29001\n'
    printf 'POSTGRES_DB=spark_x_test_platform\n'
    printf 'POSTGRES_USER=spark_x_test\n'
    printf 'POSTGRES_PASSWORD=%s\n' "$postgres_password"
    printf 'MINIO_ACCESS_KEY=spark-x-test-platform\n'
    printf 'MINIO_SECRET_KEY=%s\n' "$minio_secret"
    printf 'MINIO_BUCKET=test-artifacts\n'
    printf 'PLATFORM_QUEUE_NAME=test-runs\n'
    printf 'PLATFORM_SECRET_ENCRYPTION_KEY=%s\n' "$platform_secret_key"
    printf 'WORKER_CONCURRENCY=2\n'
    printf 'WORKER_IDENTITY=\n'
  } > "$ENV_FILE.tmp"
  mv "$ENV_FILE.tmp" "$ENV_FILE"
}

ensure_runtime_environment
chmod 600 "$ENV_FILE"

if ! grep -Eq '^PLATFORM_SECRET_ENCRYPTION_KEY=[A-Za-z0-9+/]{43}=$' "$ENV_FILE"; then
  umask 077
  grep -v '^PLATFORM_SECRET_ENCRYPTION_KEY=' "$ENV_FILE" > "$ENV_FILE.tmp"
  printf 'PLATFORM_SECRET_ENCRYPTION_KEY=%s\n' "$(openssl rand -base64 32 | tr -d '\n')" >> "$ENV_FILE.tmp"
  mv "$ENV_FILE.tmp" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
fi

if ! grep -q '^PLATFORM_CONTEXT_COMPACTION_FIXTURE_ENABLED=' "$ENV_FILE"; then
  printf 'PLATFORM_CONTEXT_COMPACTION_FIXTURE_ENABLED=true\n' >> "$ENV_FILE"
fi

if ! grep -q '^PLATFORM_SKILL_INJECTION_FIXTURE_ENABLED=' "$ENV_FILE"; then
  printf 'PLATFORM_SKILL_INJECTION_FIXTURE_ENABLED=true\n' >> "$ENV_FILE"
fi

if grep -q "change-me-local-only" "$ENV_FILE"; then
  echo "runtime environment still contains an example secret" >&2
  exit 67
fi

RELEASE_COMMIT="$(head -n 1 "$RELEASE_DIR/.youlan-commit")"
if [[ ! "$RELEASE_COMMIT" =~ ^[0-9a-f]{40}$ ]]; then
  echo "release commit marker is invalid" >&2
  exit 68
fi

VERIFIED_DIR="$SHARED_DIR/verified-commits"
BACKUP_DIR="$SHARED_DIR/backups"
COMPOSE_FILE="$RELEASE_DIR/infra/compose/compose.yaml"

run_compose() {
  PLATFORM_VERSION="$RELEASE_COMMIT" docker compose \
    --env-file "$ENV_FILE" \
    --project-name "$PROJECT_NAME" \
    -f "$COMPOSE_FILE" \
    "$@"
}

build_and_verify() {
  mkdir -p "$VERIFIED_DIR"
  run_compose build

  local marker="$VERIFIED_DIR/$RELEASE_COMMIT.ok"
  if [[ ! -f "$marker" ]]; then
    run_compose run --rm --no-deps api npm run check
    printf '%s\n' "$RELEASE_COMMIT" > "$marker.tmp"
    mv "$marker.tmp" "$marker"
  fi
}

backup_database() {
  umask 077
  mkdir -p "$BACKUP_DIR"

  local stamp
  stamp="$(date -u +%Y%m%dT%H%M%SZ)"
  local container="${PROJECT_NAME}-postgres-1"
  if ! docker ps -a --format '{{.Names}}' | grep -Fxq "$container"; then
    printf 'baseline release %s has no previous database\n' "$RELEASE_COMMIT" > "$BACKUP_DIR/${stamp}-baseline.txt"
    return 0
  fi

  local backup="$BACKUP_DIR/${stamp}-postgres.dump"
  docker exec "$container" sh -lc \
    'pg_dump -U "$POSTGRES_USER" -d "$POSTGRES_DB" -Fc' > "$backup.tmp"
  test -s "$backup.tmp"
  mv "$backup.tmp" "$backup"
  sha256sum "$backup" > "$backup.sha256"
}

run_migrations() {
  build_and_verify
  run_compose up -d postgres redis minio
  run_compose run --rm migrate
}

start_platform() {
  build_and_verify
  run_compose up -d --remove-orphans
}

stop_platform() {
  run_compose down --remove-orphans
}

wait_for_url() {
  local url="$1"
  local attempt
  for attempt in $(seq 1 60); do
    if curl -fsS --max-time 5 "$url" >/dev/null; then
      return 0
    fi
    sleep 2
  done
  echo "health endpoint did not become ready: $url" >&2
  return 1
}

smoke_platform() {
  # Runtime values are generated by the trusted release profile and contain no shell expressions.
  # shellcheck disable=SC1090
  source "$ENV_FILE"

  wait_for_url "http://127.0.0.1:${WEB_PORT}/healthz"
  wait_for_url "http://127.0.0.1:${API_PORT}/api/v1/readyz"
  wait_for_url "http://127.0.0.1:${SCHEDULER_HEALTH_PORT}/readyz"
  wait_for_url "http://127.0.0.1:${WORKER_HEALTH_PORT}/readyz"

  local migration_count
  migration_count="$(run_compose exec -T postgres psql \
    -U "$POSTGRES_USER" -d "$POSTGRES_DB" -Atqc \
    "select count(*) from platform_schema_migrations where version in ('0001_platform_bootstrap.sql', '0002_test_asset_control_plane.sql', '0003_run_evidence_loop.sql', '0004_resource_safety_loop.sql')")"
  test "$migration_count" = "4"

  local heartbeat_count
  heartbeat_count="$(run_compose exec -T postgres psql \
    -U "$POSTGRES_USER" -d "$POSTGRES_DB" -Atqc \
    "select count(distinct service_name) from service_heartbeats where service_name in ('scheduler', 'worker') and last_seen_at > now() - interval '90 seconds'")"
  test "$heartbeat_count" = "2"

  run_compose exec -T api node --import tsx scripts/verify-m3-http-run.ts
}

case "$ACTION" in
  backup) backup_database ;;
  migrate) run_migrations ;;
  start) start_platform ;;
  stop) stop_platform ;;
  smoke) smoke_platform ;;
  *)
    echo "unsupported release action: $ACTION" >&2
    exit 64
    ;;
esac
