#!/usr/bin/env bash

set -euo pipefail

ACTION="${1:-}"
RELEASE_DIR="${2:-}"
ENV_FILE="${3:-}"
PROJECT_NAME="spark-x-test-platform"

if [[ -z "$ACTION" || -z "$RELEASE_DIR" || -z "$ENV_FILE" ]]; then
  echo "usage: release.sh <backup|migrate|start|stop|smoke> <release-dir> <env-file>" >&2
  exit 64
fi

if [[ ! -d "$RELEASE_DIR" || ! -f "$RELEASE_DIR/infra/compose/compose.yaml" ]]; then
  echo "release directory is incomplete" >&2
  exit 65
fi

if [[ ! -f "$ENV_FILE" ]]; then
  echo "runtime environment file is missing" >&2
  exit 66
fi

if grep -q "change-me-local-only" "$ENV_FILE"; then
  echo "runtime environment still contains an example secret" >&2
  exit 67
fi

RELEASE_COMMIT="$(head -n 1 "$RELEASE_DIR/.youlan-commit")"
if [[ ! "$RELEASE_COMMIT" =~ ^[0-9a-f]{40}$ ]]; then
  echo "release commit marker is invalid" >&2
  exit 68
fi

SHARED_DIR="$(dirname "$ENV_FILE")"
VERIFIED_DIR="$SHARED_DIR/verified-commits"
BACKUP_DIR="$SHARED_DIR/backups"
COMPOSE_FILE="$RELEASE_DIR/infra/compose/compose.yaml"

run_compose() {
  PLATFORM_VERSION="$RELEASE_COMMIT" docker compose \
    --env-file "$ENV_FILE" \
    --project-name "$PROJECT_NAME" \
    --project-directory "$RELEASE_DIR" \
    -f "$COMPOSE_FILE" \
    "$@"
}

build_and_verify() {
  mkdir -p "$VERIFIED_DIR"
  run_compose build

  local marker="$VERIFIED_DIR/$RELEASE_COMMIT.ok"
  if [[ ! -f "$marker" ]]; then
    run_compose run --rm --no-deps api npm run check
    printf '%s\n' "$RELEASE_COMMIT" > "$marker.tmp"
    mv "$marker.tmp" "$marker"
  fi
}

backup_database() {
  umask 077
  mkdir -p "$BACKUP_DIR"

  local stamp
  stamp="$(date -u +%Y%m%dT%H%M%SZ)"
  local container="${PROJECT_NAME}-postgres-1"
  if ! docker ps -a --format '{{.Names}}' | grep -Fxq "$container"; then
    printf 'baseline release %s has no previous database\n' "$RELEASE_COMMIT" > "$BACKUP_DIR/${stamp}-baseline.txt"
    return 0
  fi

  local backup="$BACKUP_DIR/${stamp}-postgres.dump"
  docker exec "$container" sh -lc \
    'pg_dump -U "$POSTGRES_USER" -d "$POSTGRES_DB" -Fc' > "$backup.tmp"
  test -s "$backup.tmp"
  mv "$backup.tmp" "$backup"
  sha256sum "$backup" > "$backup.sha256"
}

run_migrations() {
  build_and_verify
  run_compose up -d postgres redis minio
  run_compose run --rm migrate
}

start_platform() {
  build_and_verify
  run_compose up -d --remove-orphans
}

stop_platform() {
  run_compose down --remove-orphans
}

wait_for_url() {
  local url="$1"
  local attempt
  for attempt in $(seq 1 60); do
    if curl -fsS --max-time 5 "$url" >/dev/null; then
      return 0
    fi
    sleep 2
  done
  echo "health endpoint did not become ready: $url" >&2
  return 1
}

smoke_platform() {
  # Runtime values are generated by the trusted release profile and contain no shell expressions.
  # shellcheck disable=SC1090
  source "$ENV_FILE"

  wait_for_url "http://127.0.0.1:${WEB_PORT}/healthz"
  wait_for_url "http://127.0.0.1:${API_PORT}/api/v1/readyz"
  wait_for_url "http://127.0.0.1:${SCHEDULER_HEALTH_PORT}/readyz"
  wait_for_url "http://127.0.0.1:${WORKER_HEALTH_PORT}/readyz"

  local migration_count
  migration_count="$(run_compose exec -T postgres psql \
    -U "$POSTGRES_USER" -d "$POSTGRES_DB" -Atqc \
    "select count(*) from platform_schema_migrations where version = '0001_platform_bootstrap.sql'")"
  test "$migration_count" = "1"

  local heartbeat_count
  heartbeat_count="$(run_compose exec -T postgres psql \
    -U "$POSTGRES_USER" -d "$POSTGRES_DB" -Atqc \
    "select count(distinct service_name) from service_heartbeats where service_name in ('scheduler', 'worker') and last_seen_at > now() - interval '90 seconds'")"
  test "$heartbeat_count" = "2"
}

case "$ACTION" in
  backup) backup_database ;;
  migrate) run_migrations ;;
  start) start_platform ;;
  stop) stop_platform ;;
  smoke) smoke_platform ;;
  *)
    echo "unsupported release action: $ACTION" >&2
    exit 64
    ;;
esac
